### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by 05akhiljain** [gpeipman/AspNetCoreChatRoom#1]
Hi,
I have tried to run chat application using your solution. But unable to run successfully, because web socket has not started. It gives below error:
![img_02112017_155022_0](https://user-images.githubusercontent.com/33246028/32321134-2940c5be-bfe6-11e7-8c7a-1907f7978f4b.png)
Please help me.

**Comment by gpeipman** [comment]
Hi,
on what browser this problem happens?

**Comment by 05akhiljain** [comment]
Google chrome 
Same i host the code and ty to run then i get eroror below
Error during WebSocket handshake: Unexpected response code: 404

**Comment by gpeipman** [comment]
It seems to be server-side issue. Please make sure you have WebSocket enabled in server. If you are using full IIS then WebSocket support must be enabled during setup. IIS Express should support WebSocket out-of-box. At least I didn't had to do anything additional on clean machine with IIS Express and Visual Studio.

**Comment by 05akhiljain** [comment]
hi
I am using windows 7 server can you please help me by telling how to enable web socket

**Comment by gpeipman** [comment]
WebSocket is not supported on Windows 7 by IIS. You must have Windows 8 or newer as support for WebSocket came to IIS with version 8. One option in your case is to go with SignalR but it is still in beta and there's no stable release yet for ASP.NET Core.

**Comment by 05akhiljain** [comment]
i got problem in signal r connection 
connect failed show in signal r also

**Comment by gpeipman** [comment]
Try to run Visual Studio as Administrator and see if things work then.

**Comment by 05akhiljain** [comment]
thanks for your reply but i am using published code for hosting as signalr work fine on localhost windows 7

**Comment by gpeipman** [comment]
If problem happens in some hosting environment then please consult with their support. If you are using services by some shared hosting provider then security measures can be very tough in servers.

**Comment by 05akhiljain** [comment]
ok thanks

**Comment by 05akhiljain** [comment]
HI 
Now I am using windows 8 and this code work fine for iis express but if host this code then it gives error below
Error during WebSocket handshake: Unexpected response code: 200

Please help
